name = input("Enter employee's name: ")
hour = float(input("Enter number fo hours worked in a week: "))
pay_rate = float(input("Enter pay rate: "))
fed_tax = float(input("Enter federal tax witholding: "))
state_tax = float(input("Enter state tax witholding: "))

print("Employee Name:", name)
print("Pay Rate:", pay_rate)
print("Gross Pay:", pay_rate*hour)
print("Dedcution:")
print("  Federal Witholding(", end="")
print(fed_tax*100, end="")
print("%) : $", end="")
print(format(fed_tax*pay_rate*hour, ".2f"))
print("  State Witholding(", end="")
print(state_tax*100, end="")
print("%) : $", end="")
print(format(state_tax*pay_rate*hour, ".2f"))
print("  Total Decuction: $", end="")
print(format(state_tax*pay_rate*hour + fed_tax*pay_rate*hour, ".2f"))
print("Net Pay: $", end="")
print(format(pay_rate*hour - (state_tax*pay_rate*hour + fed_tax*pay_rate*hour), ".2f"))
